### ISSUE TITLE
Fatal errors occur frequently when creating orders

### ISSUE THREAD

**Issue by aedogroup** [codeswholesale/codeswholesale-sdk-php#4]
I'm calling a simple PHP script adapted from one of your examples to create single orders. The script is run with PHP command line interface (CLI), from within a Python application. Sometimes the script works just fine, i.e. I get the expected response, a game code as either text or an image file. However, a lot of the time I get one of the following Fatal errors:

Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 65: necessary data rewind wasn't possible [url] https://api.codeswholesale.com/v1/orders?productId=a0df38b9-aacb-495a-8e7b-6b23f97aff45' in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:338
Stack trace:
#0 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 338

Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 52: Empty reply from server [url] https://api.codeswholesale.com/v1/products/552ad4af-f0b9-45e3-b303-cc3e6ff5602e' in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:338
Stack trace:
#0 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /home/pvapps/app/vendor.109/guzzle/guzzle/src/ in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 338

Fatal error: Uncaught exception 'CodesWholesale\Util\OAuthError' with message 'The access token that you've provided is not valid, check your credentials or endpoint.' in /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Http/HttpClientRequestExecutor.php:33
Stack trace:
#0 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/DataStore/DefaultDataStore.php(121): CodesWholesale\Http\HttpClientRequestExecutor->executeRequest(Object(CodesWholesale\Http\DefaultRequest))
#1 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/DataStore/DefaultDataStore.php(42): CodesWholesale\DataStore\DefaultDataStore->executeRequest('GET', 'https://api.cod...', '', Array)
#2 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Client.php(59): CodesWholesale\DataStore\DefaultDataStore->getResource('https://api.cod...', 'Product', Array)
#3 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Resource/Product.php(38): CodesWholesale\Client::get('https://api.cod...', 'Product', in /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Http/HttpClientRequestExecutor.php on line 33

The first of these is the most common, and most annoying due to the fact that the order actually succeeds but then the code needs to be downloaded from your web app. The others I could handle simply by retrying again later, before a real solution is found. I also have another simple PHP script that is run the same way, to get product updates, and that one works pretty much every time. Oh, and I'm using PdoStorage to store the auth tokens.

**Comment by codeswholesale** [comment]
Hello,

Could you send me your PHP Script where is calling method for single order? 
Also do you using LIVE_ENDPOINT or SANDBOX_ENDPOINT?




Best Regards,
Maciej



---- Wł. Śr, 08 kwi 2015 11:58:32 +0100 aedogroup&lt;notifications@github.com&gt; napisał(a) ---- 

I'm calling a simple PHP script adapted from one of your examples to create single orders. The script is run with PHP command line interface (CLI), from within a Python application. Sometimes the script works just fine, i.e. I get the expected response, a game code as either text or an image file. However, a lot of the time I get one of the following Fatal errors:
 Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 65: necessary data rewind wasn't possible [url] https://api.codeswholesale.com/v1/orders?productId=a0df38b9-aacb-495a-8e7b-6b23f97aff45' in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:338
 Stack trace:
 #0 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti-&gt;isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
 #1 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti-&gt;processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
 #2 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti-&gt;processMessages()
 #3 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti-&gt;executeHandles in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 338
 Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 52: Empty reply from server [url] https://api.codeswholesale.com/v1/products/552ad4af-f0b9-45e3-b303-cc3e6ff5602e' in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:338
 Stack trace:
 #0 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti-&gt;isCurlException(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
 #1 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti-&gt;processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
 #2 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti-&gt;processMessages()
 #3 /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti-&gt;executeHandles()
 #4 /home/pvapps/app/vendor.109/guzzle/guzzle/src/ in /home/pvapps/app/vendor.109/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 338
 Fatal error: Uncaught exception 'CodesWholesale\Util\OAuthError' with message 'The access token that you've provided is not valid, check your credentials or endpoint.' in /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Http/HttpClientRequestExecutor.php:33
 Stack trace:
 #0 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/DataStore/DefaultDataStore.php(121): CodesWholesale\Http\HttpClientRequestExecutor-&gt;executeRequest(Object(CodesWholesale\Http\DefaultRequest))
 #1 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/DataStore/DefaultDataStore.php(42): CodesWholesale\DataStore\DefaultDataStore-&gt;executeRequest('GET', 'https://api.cod...', '', Array)
 #2 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Client.php(59): CodesWholesale\DataStore\DefaultDataStore-&gt;getResource('https://api.cod...', 'Product', Array)
 #3 /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Resource/Product.php(38): CodesWholesale\Client::get('https://api.cod...', 'Product', in /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/Http/HttpClientRequestExecutor.php on line 33
 The first of these is the most common, and most annoying due to the fact that the order actually succeeds but then the code needs to be downloaded from your web app. The others I could handle simply by retrying again later, before a real solution is found. I also have another simple PHP script that is run the same way, to get product updates, and that one works pretty much every time. Oh, and I'm using PdoStorage to store the auth tokens.
 —
Reply to this email directly or view it on GitHub.
    
 
 




Best Regards,
Dev Team






Dev Team
CodesWholesale.com
Mail: devteam@codeswholesale.com
Skype: devteam.codeswholesale
Twitter: CodesWholesale

**Comment by aedogroup** [comment]
Just sent an email to devteam@codeswholesale.com with the script.
Using LIVE_ENDPOINT.

**Comment by codeswholesale** [comment]
So you got working correctly plugin which shows you this error or your already building API plugin?If yest please go to SANDBOX_ENDPOINT, this is test environment.

---- Wł. Śr, 08 kwi 2015 14:13:55 +0100 aedogroup&lt;notifications@github.com&gt; napisał(a) ---- 

Just sent an email to devteam@codeswholesale.com with the script.
 Using LIVE_ENDPOINT.
 —
Reply to this email directly or view it on GitHub.
    
 
 




Best Regards,
Dev Team






Dev Team
CodesWholesale.com
Mail: devteam@codeswholesale.com
Skype: devteam.codeswholesale
Twitter: CodesWholesale

**Comment by aedogroup** [comment]
Many real orders have been made with the script in question, the problem being that too often it fails with Fatal errors mentioned above. I do not recall having any such problem with the SANDBOX_ENDPOINT.

**Comment by codeswholesale** [comment]
Hey,

We will  check it, and we will contact with you soon.

---- Wł. Śr, 08 kwi 2015 14:29:24 +0100 aedogroup &lt;notifications@github.com&gt; napisał(a) ---- 

Many real orders have been made with the script in question, the problem being that too often it fails with Fatal errors mentioned above. I do not recall having any such problem with the SANDBOX_ENDPOINT.
 —
Reply to this email directly or view it on GitHub.
    
 
 




Best Regards,
Dev Team






Dev Team
CodesWholesale.com
Mail: devteam@codeswholesale.com
Skype: devteam.codeswholesale
Twitter: CodesWholesale

**Comment by aedogroup** [comment]
The problem is still present. However, starting from April 15 the fatal error has changed to the following:

Fatal error: Call to undefined method Guzzle\Http\Message\Response::getHttpStatus() in /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/CodesWholesaleTokenRequest.php on line 108

**Comment by codeswholesale** [comment]
Hello,Thanks for this information. We will try to handle it as soon as possible.Best Regards,Dev TeamDev TeamCodesWholesale.comMail: devteam@codeswholesale.comSkype: devteam.codeswholesaleTwitter: CodesWholesale---- On Śr, 13 maj 2015 12:49:17 +0100  aedogroup<notifications@github.com> wrote ----The problem is still present. However, starting from April 15 the fatal error has changed to the following:Fatal error: Call to undefined method GuzzleHttpMessageResponse::getHttpStatus() in /home/pvapps/app/vendor.109/codeswholesale/sdk/src/CodesWholesale/CodesWholesaleTokenRequest.php on line 108—Reply to this email directly or view it on GitHub.

**Comment by limbera** [comment]
has this been resolved?

**Comment by aedogroup** [comment]
No, it hasn't.

**Comment by limbera** [comment]
So is this when performing a standard purchase or a pre order request?

**Comment by aedogroup** [comment]
Standard. Pre-orders are very rare.

**Comment by limbera** [comment]
Can confirm I am getting the same errors.

Because of the instability of the PHP SDK I would like to write my own application. Can you release some documentation on your REST API endpoints?

**Comment by cocota38** [comment]
i Bought your woocommerce plugin and this error has not been resolved : PHP Fatal error:  Uncaught exception 'CodesWholesale\Resource\ResourceError' with message 'Invalid access token: 2bef4cb1-82f0-4d5b-9d54-76311b5dc873' in /home/......./public_html/wp-content/plugins/codeswholesale-woocommerce/vendor/codeswholesale/sdk/src/CodesWholesale/DataStore/DefaultDataStore.php:139

and Now with latest version of woocommerce new error appear 

[18-Jun-2015 08:17:00 UTC] PHP Notice:  WP_Query was called incorrectly.The shop_order_status taxonomy is no more in WooCommerce 2.2! You should use the new WooCommerce post_status instead, en savoir plus... Please see Debugging in WordPress for more information..  in /home/......./public_html/wp-includes/functions.php on line 3560


Wait since several week, write many email to devteam but nothing....i spend 200€ for a plugin with fatal errors, and I feel that your support team does not care :-1:

**Comment by codeswholesale** [comment]
Hello Cocota38,

You've wrote to us today on: 18 June 2015 10:07:22.
We recieved your message and we are working on it.
Your last error has been solved. As We notcied the new one depends on the latest version of WooCommerce, and we will fit our plugin to that as soon as it will be possible.

Excuse me for this issue.

Best Regards,
DevTeam

**Comment by cocota38** [comment]
Sorry, not understand when you say "....Your last error has been solved....".
My first message it was 01 June, since this date i send you more than 5 emails and for me nothing was solved, you send me a new version of your plugin, and the first error with invalid token and php fatal error is still there with the new plugin...... 
so i hope these 2 problems will be solved in the new version....

Thanks for help

**Comment by aedogroup** [comment]
FYI: June 29th (and most of 30th) was a good day, no errors at all. Whatever took place then, may be what you want to look at. There were no orders made on the two previous days, so can't say if they were good or not. I already had hope that you fixed the issue, but unfortunately it is back again to failing a lot.

**Comment by limbera** [comment]
are you using the SDK or the plugin aedogroup?

**Comment by aedogroup** [comment]
The SDK. From the looks of it, the problems rest on the backend.

**Comment by codeswholesale** [comment]
Hello,

We are really sorry for the issues in last couple of weeks. We've deployed API improvments and what's more all issues associated with creating orders have been solved. 

Best Regards,
Maciej

**Comment by aedogroup** [comment]
Apart from having no problems on June 29th, there has been no change to this issue. It has been three _months_ now at least.

**Comment by aedogroup** [comment]
Please, try to at least fix the error that returns with an empty message with no status code and no error code. That one occurs on an almost daily basis, too. It happened today (Aug 3) at 13:01:01 EEST. If you need other dates and times, I can give you more than a hundred..

**Comment by codeswholesale** [comment]
Hello Aedo Group,

Can we contact on mail or skype to describe us this issue more clearly?


For whole issues we provide our customers, customer service:


Skype: devteam.codeswholesale
Mail: devteam@codeswholesale.com
 
We don't recieve any infromation about that is issue from you.




Best Regards,
Maciej

---- Wł. Pn, 03 sie 2015 11:13:13 +0100 Aedo Group&lt;notifications@github.com&gt; napisał(a) ---- 

Please, try to at least fix the error that returns with an empty message with no status code and no error code. That one occurs on an almost daily basis, too. It happened today (Aug 3) at 13:01:01 EEST. If you need other dates and times, I can give you more than a hundred..
 —
Reply to this email directly or view it on GitHub.
    
 
 




Best Regards,
Dev Team






Dev Team
CodesWholesale.com
Mail: devteam@codeswholesale.com
Skype: devteam.codeswholesale
Twitter: CodesWholesale

**Comment by OogieBoogieInJSON** [comment]
Can I get the rest api docs ? I want to build my shop in node but now i'm using php as a middleman and it sucks.

**Comment by codeswholesale** [comment]
Hey OogieBoogieInJSON,

Please visit our: docs.codeswholesale.com

**Comment by limbera** [comment]
I would also like the rest api docs, but it seems all you provide is a PHP SDK. Please can you provide a detailed documentation of the rest endpoints? I want to build the store in Python...

**Comment by OogieBoogieInJSON** [comment]
Huh, thx

**Comment by limbera** [comment]
Are there any REST api docs? as OogieBoogieInJSON says, I do not want to use the PHP SDK I want to write my app in python.

**Comment by OogieBoogieInJSON** [comment]
@limbera:  Yes, there is: http://docs.codeswholesale.com .
